apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: deploy-orders-tr
spec:
  serviceAccountName: orders-sa
  taskRef:
    name: deploy-orders-t
  resources:
    inputs:
    - name: level-3-project
      resourceRef:
        name: level-3-project 
