apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: orders-pr
spec:
  pipelineRef:
    name: orders-p 
  serviceAccountName: sock-shop-sa
  resources:
    - name: level-3-project
      resourceRef:
        name: level-3-project 
