apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: deploy-payment-tr
spec:
  serviceAccountName: payment-sa
  taskRef:
    name: deploy-payment-t
  resources:
    inputs:
    - name: level-3-project
      resourceRef:
        name: level-3-project
