apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: payment-p 
spec:
  resources:
    - name:  level-3-project
      type: git
  tasks:
    - name: build
      taskRef:
        name: sock-payment-t
      resources:
        inputs: 
        - name: level-3-project
          resource: level-3-project 
    - name: deploy
      runAfter: ["build"]
      taskRef:
        name: deploy-payment-t 
      resources:
        inputs: 
        - name: level-3-project
          resource: level-3-project
