apiVersion: v1
kind: Secret
metadata:
  name: tekton-storage
  namespace: tekton-pipelines
type: kubernetes.io/opaque
stringData:
  boto-config: |
    [Credentials]
    aws_access_key_id = AKIA3H33RTPCFVX7CO5K
    aws_secret_access_key = 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
    [s3]
    host = s3.me-south-1.amazonaws.com
    [Boto]
    https_validate_certificates = True
