apiVersion: v1
kind: ServiceAccount
metadata:
  name: sock-shop-sa
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: sock-shop-r
rules:
- apiGroups: ["", "extensions", "apps"]
  resources: ["services","secrets","deployments", "deployments.apps", "replicasets", "pods"]
  verbs: ["*"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: sock-shop-rb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: sock-shop-r
subjects:
  - kind: ServiceAccount
    name: sock-shop-sa 
