apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: deploy-shipping-tr
spec:
  serviceAccountName: shipping-sa
  taskRef:
    name: deploy-shipping-t
  resources:
    inputs:
    - name: level-3-project
      resourceRef:
        name: sock-shipping
