apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: shipping-test-tr
spec:
  serviceAccountName: shipping-sa
  taskRef:
    name: shipping-t
  resources:
    inputs:
    - name: level-3-project
      resourceRef:
        name: level-3-project
