apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: shipping-tr
  namespace: test
spec:
  serviceAccountName: shipping-sa
  taskRef:
    name: sock-shipping-t
  resources:
    inputs:
    - name: level-3-project
      resourceRef:
        name: level-3-project
