apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: deploy-queue-master-tr
spec:
  serviceAccountName: queue-master-sa
  taskRef:
    name: deploy-queue-master-t
  resources:
    inputs:
    - name: level-3-project
      resourceRef:
        name: level-3-project 
