apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: front-end-p 
spec:
  params:
    - name: namespace
      type: string
      default: "test"
  resources:
    - name: level-3-project 
      type: git
  tasks:
    - name: build
      taskRef:
        name: sock-front-end-t
      resources:
        inputs: 
        - name: level-3-project
          resource: level-3-project
    - name: deploy-to-test
      runAfter: ["build"]
      taskRef:
        name: deploy-front-end-t 
      params:
      - name: ns
        value: "$(params.namespace)"
      resources:
        inputs: 
        - name: level-3-project
          resource: level-3-project
#    - name: testing 
#     runAfter: ["deploy-to-test"]
#     taskRef:
#        name: front-end-test
#      resources:
#        inputs:
#        - name: level-3-project
#          resource: level-3-project
#    - name: production
#      runAfter: ["testing"]
#      taskRef:
#        name: production
#      resources:
#        inputs: 
#        - name: level-3-project
#          resource: level-3-project
