apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: cart-test-tr
spec:
  serviceAccountName: cart-sa
  taskRef:
    name: cart-test
  resources:
    inputs:
    - name: level-3-project
      resourceRef:
        name: level-3-project
