apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: cart-p 
spec:
  resources:
    - name: sock-cart 
      type: git
  tasks:
    - name: build
      taskRef:
        name: sock-cart-t
      resources:
        inputs: 
        - name: sock-cart
          resource: sock-cart
    - name: deploy
      taskRef:
        name: deploy-cart-t 
      resources:
        inputs: 
        - name: sock-cart
          resource: sock-cart
