---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sock-cart-t
  labels:
    name: cart
spec:
  replicas: 1
  selector:
    matchLabels:
      name: cart
  template:
    metadata:
      labels:
        name: cart
    spec:
      containers:
      - name: cart
        image: manarabdulrahman/sock-cart 
        ports:
         - containerPort: 80
        volumeMounts:
        - mountPath: /tmp
          name: tmp-volume
      volumes:
        - name: tmp-volume
          emptyDir:
            medium: Memory
      nodeSelector:
        beta.kubernetes.io/os: linux
---
apiVersion: v1
kind: Service
metadata:
  name: cart
  labels:
    name: cart
spec:
  ports:
    # the port that this service should serve on
  - port: 80
    targetPort: 80
    type: NodePort
  selector:
    name: cart
