apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: load-test-tr
  namespace: test
spec:
  serviceAccountName: load-test-sa
  taskRef:
    name: sock-load-test-t
  params:
  - name: IMAGE
    value: "manarabdulrahman/sock-load-test"
  resources:
    inputs:
    - name: level-3-project
      resourceRef:
        name: sock-load-test
