apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: e2e-test-pr
spec:
  pipelineRef:
    name: e2e-test-pl 
  serviceAccountName: e2e-test-sa
  resources:
    - name: level-3-project 
      resourceRef:
        name: level-3-project 
