apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: e2e-test-pl
spec:
  resources:
    - name: level-3-project 
      type: git
  tasks:
    - name: clone-build 
      taskRef:
        name: e2e-test-t
      resources:
        inputs: 
        - name: level-3-project
          resource: level-3-project
    - name: testing
      runAfter: ["clone-build"]
      taskRef:
        name: e2e-test-dep-t 
      resources:
        inputs: 
        - name: level-3-project
          resource: level-3-project 
