apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: queue-master-pr
spec:
  pipelineRef:
    name: queue-master-p 
  serviceAccountName: queue-master-sa
  resources:
    - name: level-3-project 
      resourceRef:
        name: level-3-project 
