apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: e2e-test-tr
spec:
  serviceAccountName: e2e-test-sa 
  taskRef:
    name: e2e-test-t
  resources:
    inputs:
    - name: level-3-project
      resourceRef:
        name: level-3-project 
