apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: catalogue-p 
spec:
  resources:
    - name: level-3-project 
      type: git
  tasks:
    - name: build
      taskRef:
        name: sock-catalogue-t
      resources:
        inputs: 
        - name: level-3-project 
          resource: level-3-project
    - name: deploy-to-test
      runAfter: ["build"]
      taskRef:
        name: deploy-catalogue-t 
      resources:
        inputs: 
        - name: level-3-project
          resource: level-3-project
    - name: testing 
      runAfter: ["deploy-to-test"]
      taskRef:
        name: catalogue-test
      resources:
        inputs:
        - name: level-3-project
          resource: level-3-project
    - name: production
      runAfter: ["testing"]
      taskRef:
        name: production
      resources:
        inputs: 
        - name: level-3-project
          resource: level-3-project
