apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: catalogue-p 
spec:
  resources:
    - name: sock-catalogue 
      type: git
  tasks:
    - name: build
      taskRef:
        name: sock-catalogue-t
      resources:
        inputs: 
        - name: level-3-project 
          resource: level-3-project
    - name: deploy
      runAfter: ["build"]
      taskRef:
        name: deploy-catalogue-t 
      resources:
        inputs: 
        - name: level-3-project
          resource: level-3-project
