apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: shipping-p 
spec:
  resources:
    - name: level-3-project 
      type: git
  tasks:
    - name: build
      taskRef:
        name: sock-shipping-t
      resources:
        inputs: 
        - name: level-3-master 
          resource: level-3-project
    - name: deploy
      taskRef:
        name: deploy-shipping-t 
      resources:
        inputs: 
        - name: level-3-master
          resource: level-3-project 
