apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: user-p 
spec:
  resources:
    - name: level-3-project 
      type: git
  tasks:
    - name: build
      taskRef:
        name: sock-user-t
      resources:
        inputs: 
        - name: level-3-project
          resource: level-3-project
    - name: deploy
      runAfter: ["build"]
      taskRef:
        name: deploy-user-t 
      resources:
        inputs: 
        - name: level-3-project
          resource: level-3-project 
