apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: deploy-user-tr
spec:
  serviceAccountName: shipping-sa
  taskRef:
    name: deploy-user-t
  resources:
    inputs:
    - name: level-3-project
      resourceRef:
        name: level-3-project 
