apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: user-tr
spec:
  serviceAccountName: user-sa
  taskRef:
    name: sock-user-t
  resources:
    inputs:
    - name: level-3-project
      resourceRef:
        name: level-3-project 
