apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: docker-runner
spec:
  serviceAccountName: docker-hub
  taskRef:
    name: docker
  params:
  - name: IMAGE
    value: "manarabdulrahman/sock-user"
  resources:
    inputs:
    - name: level-3-project 
      resourceRef:
        name: level-3-project 
